// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Smart_Lab_OS.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Tangerine.Grpc.Foundation {
  /// <summary>
  /// 平台初始化服务
  /// </summary>
  public static partial class PlatformInitService
  {
    static readonly string __ServiceName = "smartlab.PlatformInitService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.InitializeRequest> __Marshaller_smartlab_InitializeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.InitializeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.Status> __Marshaller_smartlab_Status = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.Status.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.InitializeRequest, global::Tangerine.Grpc.Foundation.Status> __Method_Initialize = new grpc::Method<global::Tangerine.Grpc.Foundation.InitializeRequest, global::Tangerine.Grpc.Foundation.Status>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Initialize",
        __Marshaller_smartlab_InitializeRequest,
        __Marshaller_smartlab_Status);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Tangerine.Grpc.Foundation.SmartLabOSReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PlatformInitService</summary>
    [grpc::BindServiceMethod(typeof(PlatformInitService), "BindService")]
    public abstract partial class PlatformInitServiceBase
    {
      /// <summary>
      ///
      /// 初始化
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.Status> Initialize(global::Tangerine.Grpc.Foundation.InitializeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(PlatformInitServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Initialize, serviceImpl.Initialize).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PlatformInitServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Initialize, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.InitializeRequest, global::Tangerine.Grpc.Foundation.Status>(serviceImpl.Initialize));
    }

  }
  /// <summary>
  /// 平台运行时控制服务
  /// </summary>
  public static partial class PlatformRuntimeService
  {
    static readonly string __ServiceName = "smartlab.PlatformRuntimeService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.PlatformRequest> __Marshaller_smartlab_PlatformRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.PlatformRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.PlatformStatusResponseMessage> __Marshaller_smartlab_PlatformStatusResponseMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.PlatformStatusResponseMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.Status> __Marshaller_smartlab_Status = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.Status.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.AlarmEvent> __Marshaller_smartlab_AlarmEvent = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.AlarmEvent.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.PlatformStatusResponseMessage> __Method_GetPlatformStatus = new grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.PlatformStatusResponseMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPlatformStatus",
        __Marshaller_smartlab_PlatformRequest,
        __Marshaller_smartlab_PlatformStatusResponseMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status> __Method_ResetPlatform = new grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ResetPlatform",
        __Marshaller_smartlab_PlatformRequest,
        __Marshaller_smartlab_Status);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status> __Method_PausePlatform = new grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PausePlatform",
        __Marshaller_smartlab_PlatformRequest,
        __Marshaller_smartlab_Status);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status> __Method_ResumePlatform = new grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ResumePlatform",
        __Marshaller_smartlab_PlatformRequest,
        __Marshaller_smartlab_Status);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status> __Method_StopPlatform = new grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StopPlatform",
        __Marshaller_smartlab_PlatformRequest,
        __Marshaller_smartlab_Status);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status> __Method_StartPlatform = new grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartPlatform",
        __Marshaller_smartlab_PlatformRequest,
        __Marshaller_smartlab_Status);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.AlarmEvent> __Method_GetPlatformAlarms = new grpc::Method<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.AlarmEvent>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetPlatformAlarms",
        __Marshaller_smartlab_PlatformRequest,
        __Marshaller_smartlab_AlarmEvent);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Tangerine.Grpc.Foundation.SmartLabOSReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of PlatformRuntimeService</summary>
    [grpc::BindServiceMethod(typeof(PlatformRuntimeService), "BindService")]
    public abstract partial class PlatformRuntimeServiceBase
    {
      /// <summary>
      ///
      /// 获取平台状态
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.PlatformStatusResponseMessage> GetPlatformStatus(global::Tangerine.Grpc.Foundation.PlatformRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 复位
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.Status> ResetPlatform(global::Tangerine.Grpc.Foundation.PlatformRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 暂停
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.Status> PausePlatform(global::Tangerine.Grpc.Foundation.PlatformRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 恢复
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.Status> ResumePlatform(global::Tangerine.Grpc.Foundation.PlatformRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 停止
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.Status> StopPlatform(global::Tangerine.Grpc.Foundation.PlatformRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 启动平台
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.Status> StartPlatform(global::Tangerine.Grpc.Foundation.PlatformRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 平台告警信息流
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetPlatformAlarms(global::Tangerine.Grpc.Foundation.PlatformRequest request, grpc::IServerStreamWriter<global::Tangerine.Grpc.Foundation.AlarmEvent> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(PlatformRuntimeServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetPlatformStatus, serviceImpl.GetPlatformStatus)
          .AddMethod(__Method_ResetPlatform, serviceImpl.ResetPlatform)
          .AddMethod(__Method_PausePlatform, serviceImpl.PausePlatform)
          .AddMethod(__Method_ResumePlatform, serviceImpl.ResumePlatform)
          .AddMethod(__Method_StopPlatform, serviceImpl.StopPlatform)
          .AddMethod(__Method_StartPlatform, serviceImpl.StartPlatform)
          .AddMethod(__Method_GetPlatformAlarms, serviceImpl.GetPlatformAlarms).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PlatformRuntimeServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetPlatformStatus, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.PlatformStatusResponseMessage>(serviceImpl.GetPlatformStatus));
      serviceBinder.AddMethod(__Method_ResetPlatform, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status>(serviceImpl.ResetPlatform));
      serviceBinder.AddMethod(__Method_PausePlatform, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status>(serviceImpl.PausePlatform));
      serviceBinder.AddMethod(__Method_ResumePlatform, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status>(serviceImpl.ResumePlatform));
      serviceBinder.AddMethod(__Method_StopPlatform, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status>(serviceImpl.StopPlatform));
      serviceBinder.AddMethod(__Method_StartPlatform, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.Status>(serviceImpl.StartPlatform));
      serviceBinder.AddMethod(__Method_GetPlatformAlarms, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Tangerine.Grpc.Foundation.PlatformRequest, global::Tangerine.Grpc.Foundation.AlarmEvent>(serviceImpl.GetPlatformAlarms));
    }

  }
  /// <summary>
  /// 平台任务服务
  /// </summary>
  public static partial class PlatformTaskService
  {
    static readonly string __ServiceName = "smartlab.PlatformTaskService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.PrepareTaskRequest> __Marshaller_smartlab_PrepareTaskRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.PrepareTaskRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.Status> __Marshaller_smartlab_Status = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.Status.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.SetupTaskRequest> __Marshaller_smartlab_SetupTaskRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.SetupTaskRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.StartTaskRequest> __Marshaller_smartlab_StartTaskRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.StartTaskRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TaskEvent> __Marshaller_smartlab_TaskEvent = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TaskEvent.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.StoreTaskRequest> __Marshaller_smartlab_StoreTaskRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.StoreTaskRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.FinalizeTaskRequest> __Marshaller_smartlab_FinalizeTaskRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.FinalizeTaskRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TaskTracesRequest> __Marshaller_smartlab_TaskTracesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TaskTracesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TaskTracesReply> __Marshaller_smartlab_TaskTracesReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TaskTracesReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TaskTrayUsageRequest> __Marshaller_smartlab_TaskTrayUsageRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TaskTrayUsageRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TaskTrayUsageReply> __Marshaller_smartlab_TaskTrayUsageReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TaskTrayUsageReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TaskTrayLabwareInfoRequest> __Marshaller_smartlab_TaskTrayLabwareInfoRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TaskTrayLabwareInfoRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TaskTrayLabwareInfoReply> __Marshaller_smartlab_TaskTrayLabwareInfoReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TaskTrayLabwareInfoReply.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TaskTrayInitialBindingInfoRequest> __Marshaller_smartlab_TaskTrayInitialBindingInfoRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TaskTrayInitialBindingInfoRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TaskTrayInitialBindingInfoReply> __Marshaller_smartlab_TaskTrayInitialBindingInfoReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TaskTrayInitialBindingInfoReply.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.PrepareTaskRequest, global::Tangerine.Grpc.Foundation.Status> __Method_PrepareTask = new grpc::Method<global::Tangerine.Grpc.Foundation.PrepareTaskRequest, global::Tangerine.Grpc.Foundation.Status>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PrepareTask",
        __Marshaller_smartlab_PrepareTaskRequest,
        __Marshaller_smartlab_Status);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.SetupTaskRequest, global::Tangerine.Grpc.Foundation.Status> __Method_SetupTask = new grpc::Method<global::Tangerine.Grpc.Foundation.SetupTaskRequest, global::Tangerine.Grpc.Foundation.Status>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetupTask",
        __Marshaller_smartlab_SetupTaskRequest,
        __Marshaller_smartlab_Status);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.StartTaskRequest, global::Tangerine.Grpc.Foundation.TaskEvent> __Method_StartTask = new grpc::Method<global::Tangerine.Grpc.Foundation.StartTaskRequest, global::Tangerine.Grpc.Foundation.TaskEvent>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "StartTask",
        __Marshaller_smartlab_StartTaskRequest,
        __Marshaller_smartlab_TaskEvent);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.StoreTaskRequest, global::Tangerine.Grpc.Foundation.Status> __Method_StoreTask = new grpc::Method<global::Tangerine.Grpc.Foundation.StoreTaskRequest, global::Tangerine.Grpc.Foundation.Status>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StoreTask",
        __Marshaller_smartlab_StoreTaskRequest,
        __Marshaller_smartlab_Status);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.FinalizeTaskRequest, global::Tangerine.Grpc.Foundation.Status> __Method_FinalizeTask = new grpc::Method<global::Tangerine.Grpc.Foundation.FinalizeTaskRequest, global::Tangerine.Grpc.Foundation.Status>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FinalizeTask",
        __Marshaller_smartlab_FinalizeTaskRequest,
        __Marshaller_smartlab_Status);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.TaskTracesRequest, global::Tangerine.Grpc.Foundation.TaskTracesReply> __Method_GetTaskTraces = new grpc::Method<global::Tangerine.Grpc.Foundation.TaskTracesRequest, global::Tangerine.Grpc.Foundation.TaskTracesReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTaskTraces",
        __Marshaller_smartlab_TaskTracesRequest,
        __Marshaller_smartlab_TaskTracesReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.TaskTrayUsageRequest, global::Tangerine.Grpc.Foundation.TaskTrayUsageReply> __Method_GetTaskTraykUsage = new grpc::Method<global::Tangerine.Grpc.Foundation.TaskTrayUsageRequest, global::Tangerine.Grpc.Foundation.TaskTrayUsageReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTaskTraykUsage",
        __Marshaller_smartlab_TaskTrayUsageRequest,
        __Marshaller_smartlab_TaskTrayUsageReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.TaskTrayLabwareInfoRequest, global::Tangerine.Grpc.Foundation.TaskTrayLabwareInfoReply> __Method_GetTaskTrayLabwareInfo = new grpc::Method<global::Tangerine.Grpc.Foundation.TaskTrayLabwareInfoRequest, global::Tangerine.Grpc.Foundation.TaskTrayLabwareInfoReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTaskTrayLabwareInfo",
        __Marshaller_smartlab_TaskTrayLabwareInfoRequest,
        __Marshaller_smartlab_TaskTrayLabwareInfoReply);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.TaskTrayInitialBindingInfoRequest, global::Tangerine.Grpc.Foundation.TaskTrayInitialBindingInfoReply> __Method_GetTrayInitialBindingInfo = new grpc::Method<global::Tangerine.Grpc.Foundation.TaskTrayInitialBindingInfoRequest, global::Tangerine.Grpc.Foundation.TaskTrayInitialBindingInfoReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTrayInitialBindingInfo",
        __Marshaller_smartlab_TaskTrayInitialBindingInfoRequest,
        __Marshaller_smartlab_TaskTrayInitialBindingInfoReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Tangerine.Grpc.Foundation.SmartLabOSReflection.Descriptor.Services[2]; }
    }

    /// <summary>Base class for server-side implementations of PlatformTaskService</summary>
    [grpc::BindServiceMethod(typeof(PlatformTaskService), "BindService")]
    public abstract partial class PlatformTaskServiceBase
    {
      /// <summary>
      ///
      /// 准备实验任务
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.Status> PrepareTask(global::Tangerine.Grpc.Foundation.PrepareTaskRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 设置开始任务参数
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.Status> SetupTask(global::Tangerine.Grpc.Foundation.SetupTaskRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 开始实验任务
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task StartTask(global::Tangerine.Grpc.Foundation.StartTaskRequest request, grpc::IServerStreamWriter<global::Tangerine.Grpc.Foundation.TaskEvent> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 实验封存
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.Status> StoreTask(global::Tangerine.Grpc.Foundation.StoreTaskRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 实验收尾
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.Status> FinalizeTask(global::Tangerine.Grpc.Foundation.FinalizeTaskRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 获取任务追踪信息
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.TaskTracesReply> GetTaskTraces(global::Tangerine.Grpc.Foundation.TaskTracesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 获取任务中托盘使用情况
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.TaskTrayUsageReply> GetTaskTraykUsage(global::Tangerine.Grpc.Foundation.TaskTrayUsageRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 获取任务中托盘器皿信息
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.TaskTrayLabwareInfoReply> GetTaskTrayLabwareInfo(global::Tangerine.Grpc.Foundation.TaskTrayLabwareInfoRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 获取任务中各孔位首次扫码绑定信息
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.TaskTrayInitialBindingInfoReply> GetTrayInitialBindingInfo(global::Tangerine.Grpc.Foundation.TaskTrayInitialBindingInfoRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(PlatformTaskServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PrepareTask, serviceImpl.PrepareTask)
          .AddMethod(__Method_SetupTask, serviceImpl.SetupTask)
          .AddMethod(__Method_StartTask, serviceImpl.StartTask)
          .AddMethod(__Method_StoreTask, serviceImpl.StoreTask)
          .AddMethod(__Method_FinalizeTask, serviceImpl.FinalizeTask)
          .AddMethod(__Method_GetTaskTraces, serviceImpl.GetTaskTraces)
          .AddMethod(__Method_GetTaskTraykUsage, serviceImpl.GetTaskTraykUsage)
          .AddMethod(__Method_GetTaskTrayLabwareInfo, serviceImpl.GetTaskTrayLabwareInfo)
          .AddMethod(__Method_GetTrayInitialBindingInfo, serviceImpl.GetTrayInitialBindingInfo).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PlatformTaskServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_PrepareTask, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.PrepareTaskRequest, global::Tangerine.Grpc.Foundation.Status>(serviceImpl.PrepareTask));
      serviceBinder.AddMethod(__Method_SetupTask, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.SetupTaskRequest, global::Tangerine.Grpc.Foundation.Status>(serviceImpl.SetupTask));
      serviceBinder.AddMethod(__Method_StartTask, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Tangerine.Grpc.Foundation.StartTaskRequest, global::Tangerine.Grpc.Foundation.TaskEvent>(serviceImpl.StartTask));
      serviceBinder.AddMethod(__Method_StoreTask, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.StoreTaskRequest, global::Tangerine.Grpc.Foundation.Status>(serviceImpl.StoreTask));
      serviceBinder.AddMethod(__Method_FinalizeTask, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.FinalizeTaskRequest, global::Tangerine.Grpc.Foundation.Status>(serviceImpl.FinalizeTask));
      serviceBinder.AddMethod(__Method_GetTaskTraces, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.TaskTracesRequest, global::Tangerine.Grpc.Foundation.TaskTracesReply>(serviceImpl.GetTaskTraces));
      serviceBinder.AddMethod(__Method_GetTaskTraykUsage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.TaskTrayUsageRequest, global::Tangerine.Grpc.Foundation.TaskTrayUsageReply>(serviceImpl.GetTaskTraykUsage));
      serviceBinder.AddMethod(__Method_GetTaskTrayLabwareInfo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.TaskTrayLabwareInfoRequest, global::Tangerine.Grpc.Foundation.TaskTrayLabwareInfoReply>(serviceImpl.GetTaskTrayLabwareInfo));
      serviceBinder.AddMethod(__Method_GetTrayInitialBindingInfo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.TaskTrayInitialBindingInfoRequest, global::Tangerine.Grpc.Foundation.TaskTrayInitialBindingInfoReply>(serviceImpl.GetTrayInitialBindingInfo));
    }

  }
  /// <summary>
  /// 平台监控服务
  /// </summary>
  public static partial class PlatformMonitorService
  {
    static readonly string __ServiceName = "smartlab.PlatformMonitorService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.StartMonitorRequest> __Marshaller_smartlab_StartMonitorRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.StartMonitorRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.MonitorEvent> __Marshaller_smartlab_MonitorEvent = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.MonitorEvent.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.MonitorSnapshotRequest> __Marshaller_smartlab_MonitorSnapshotRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.MonitorSnapshotRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.StartMonitorRequest, global::Tangerine.Grpc.Foundation.MonitorEvent> __Method_StartMonitor = new grpc::Method<global::Tangerine.Grpc.Foundation.StartMonitorRequest, global::Tangerine.Grpc.Foundation.MonitorEvent>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "StartMonitor",
        __Marshaller_smartlab_StartMonitorRequest,
        __Marshaller_smartlab_MonitorEvent);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.MonitorSnapshotRequest, global::Tangerine.Grpc.Foundation.MonitorEvent> __Method_GetMonitorSnapshot = new grpc::Method<global::Tangerine.Grpc.Foundation.MonitorSnapshotRequest, global::Tangerine.Grpc.Foundation.MonitorEvent>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMonitorSnapshot",
        __Marshaller_smartlab_MonitorSnapshotRequest,
        __Marshaller_smartlab_MonitorEvent);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Tangerine.Grpc.Foundation.SmartLabOSReflection.Descriptor.Services[3]; }
    }

    /// <summary>Base class for server-side implementations of PlatformMonitorService</summary>
    [grpc::BindServiceMethod(typeof(PlatformMonitorService), "BindService")]
    public abstract partial class PlatformMonitorServiceBase
    {
      /// <summary>
      ///
      /// 监控流
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task StartMonitor(global::Tangerine.Grpc.Foundation.StartMonitorRequest request, grpc::IServerStreamWriter<global::Tangerine.Grpc.Foundation.MonitorEvent> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 获取监控快照
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.MonitorEvent> GetMonitorSnapshot(global::Tangerine.Grpc.Foundation.MonitorSnapshotRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(PlatformMonitorServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_StartMonitor, serviceImpl.StartMonitor)
          .AddMethod(__Method_GetMonitorSnapshot, serviceImpl.GetMonitorSnapshot).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PlatformMonitorServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_StartMonitor, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Tangerine.Grpc.Foundation.StartMonitorRequest, global::Tangerine.Grpc.Foundation.MonitorEvent>(serviceImpl.StartMonitor));
      serviceBinder.AddMethod(__Method_GetMonitorSnapshot, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.MonitorSnapshotRequest, global::Tangerine.Grpc.Foundation.MonitorEvent>(serviceImpl.GetMonitorSnapshot));
    }

  }
  /// <summary>
  /// 配置管理服务
  /// </summary>
  public static partial class ConfigService
  {
    static readonly string __ServiceName = "smartlab.ConfigService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.LaboratoryDefinition> __Marshaller_smartlab_LaboratoryDefinition = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.LaboratoryDefinition.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Tangerine.Grpc.Foundation.LaboratoryDefinition> __Method_GetLaboratoryConfigs = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Tangerine.Grpc.Foundation.LaboratoryDefinition>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLaboratoryConfigs",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_smartlab_LaboratoryDefinition);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Tangerine.Grpc.Foundation.SmartLabOSReflection.Descriptor.Services[4]; }
    }

    /// <summary>Base class for server-side implementations of ConfigService</summary>
    [grpc::BindServiceMethod(typeof(ConfigService), "BindService")]
    public abstract partial class ConfigServiceBase
    {
      /// <summary>
      ///
      /// 获取实验室配置
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.LaboratoryDefinition> GetLaboratoryConfigs(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ConfigServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetLaboratoryConfigs, serviceImpl.GetLaboratoryConfigs).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ConfigServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetLaboratoryConfigs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Tangerine.Grpc.Foundation.LaboratoryDefinition>(serviceImpl.GetLaboratoryConfigs));
    }

  }
  /// <summary>
  /// 平台中转服务
  /// </summary>
  public static partial class PlatformTransferService
  {
    static readonly string __ServiceName = "smartlab.PlatformTransferService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TransferInitRequest> __Marshaller_smartlab_TransferInitRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TransferInitRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TransferInitResponseMessage> __Marshaller_smartlab_TransferInitResponseMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TransferInitResponseMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TransferStatusRequest> __Marshaller_smartlab_TransferStatusRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TransferStatusRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TransferStatusResponseMessage> __Marshaller_smartlab_TransferStatusResponseMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TransferStatusResponseMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TransferTrayMoveRequest> __Marshaller_smartlab_TransferTrayMoveRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TransferTrayMoveRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TransferTrayMoveResponse> __Marshaller_smartlab_TransferTrayMoveResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TransferTrayMoveResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.UnloadTransferToLoadTransferRequest> __Marshaller_smartlab_UnloadTransferToLoadTransferRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.UnloadTransferToLoadTransferRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.UnloadTransferToLoadTransferResponse> __Marshaller_smartlab_UnloadTransferToLoadTransferResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.UnloadTransferToLoadTransferResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.LoadTransferToUnloadTransferRequest> __Marshaller_smartlab_LoadTransferToUnloadTransferRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.LoadTransferToUnloadTransferRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.LoadTransferToUnloadTransferResponse> __Marshaller_smartlab_LoadTransferToUnloadTransferResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.LoadTransferToUnloadTransferResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TransferMoveRequest> __Marshaller_smartlab_TransferMoveRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TransferMoveRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Tangerine.Grpc.Foundation.TransferMoveResponseMessage> __Marshaller_smartlab_TransferMoveResponseMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Tangerine.Grpc.Foundation.TransferMoveResponseMessage.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.TransferInitRequest, global::Tangerine.Grpc.Foundation.TransferInitResponseMessage> __Method_TransferInit = new grpc::Method<global::Tangerine.Grpc.Foundation.TransferInitRequest, global::Tangerine.Grpc.Foundation.TransferInitResponseMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransferInit",
        __Marshaller_smartlab_TransferInitRequest,
        __Marshaller_smartlab_TransferInitResponseMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.TransferStatusRequest, global::Tangerine.Grpc.Foundation.TransferStatusResponseMessage> __Method_GetTransferStatus = new grpc::Method<global::Tangerine.Grpc.Foundation.TransferStatusRequest, global::Tangerine.Grpc.Foundation.TransferStatusResponseMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTransferStatus",
        __Marshaller_smartlab_TransferStatusRequest,
        __Marshaller_smartlab_TransferStatusResponseMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.TransferTrayMoveRequest, global::Tangerine.Grpc.Foundation.TransferTrayMoveResponse> __Method_TrayToTransfer = new grpc::Method<global::Tangerine.Grpc.Foundation.TransferTrayMoveRequest, global::Tangerine.Grpc.Foundation.TransferTrayMoveResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TrayToTransfer",
        __Marshaller_smartlab_TransferTrayMoveRequest,
        __Marshaller_smartlab_TransferTrayMoveResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.TransferTrayMoveRequest, global::Tangerine.Grpc.Foundation.TransferTrayMoveResponse> __Method_TransferToTray = new grpc::Method<global::Tangerine.Grpc.Foundation.TransferTrayMoveRequest, global::Tangerine.Grpc.Foundation.TransferTrayMoveResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransferToTray",
        __Marshaller_smartlab_TransferTrayMoveRequest,
        __Marshaller_smartlab_TransferTrayMoveResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.UnloadTransferToLoadTransferRequest, global::Tangerine.Grpc.Foundation.UnloadTransferToLoadTransferResponse> __Method_UnloadTransferToLoadTransfer = new grpc::Method<global::Tangerine.Grpc.Foundation.UnloadTransferToLoadTransferRequest, global::Tangerine.Grpc.Foundation.UnloadTransferToLoadTransferResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UnloadTransferToLoadTransfer",
        __Marshaller_smartlab_UnloadTransferToLoadTransferRequest,
        __Marshaller_smartlab_UnloadTransferToLoadTransferResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.LoadTransferToUnloadTransferRequest, global::Tangerine.Grpc.Foundation.LoadTransferToUnloadTransferResponse> __Method_LoadTransferToUnloadTransfer = new grpc::Method<global::Tangerine.Grpc.Foundation.LoadTransferToUnloadTransferRequest, global::Tangerine.Grpc.Foundation.LoadTransferToUnloadTransferResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "LoadTransferToUnloadTransfer",
        __Marshaller_smartlab_LoadTransferToUnloadTransferRequest,
        __Marshaller_smartlab_LoadTransferToUnloadTransferResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.TransferMoveRequest, global::Tangerine.Grpc.Foundation.TransferMoveResponseMessage> __Method_TransferForward = new grpc::Method<global::Tangerine.Grpc.Foundation.TransferMoveRequest, global::Tangerine.Grpc.Foundation.TransferMoveResponseMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransferForward",
        __Marshaller_smartlab_TransferMoveRequest,
        __Marshaller_smartlab_TransferMoveResponseMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Tangerine.Grpc.Foundation.TransferMoveRequest, global::Tangerine.Grpc.Foundation.TransferMoveResponseMessage> __Method_TransferBackward = new grpc::Method<global::Tangerine.Grpc.Foundation.TransferMoveRequest, global::Tangerine.Grpc.Foundation.TransferMoveResponseMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransferBackward",
        __Marshaller_smartlab_TransferMoveRequest,
        __Marshaller_smartlab_TransferMoveResponseMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Tangerine.Grpc.Foundation.SmartLabOSReflection.Descriptor.Services[5]; }
    }

    /// <summary>Base class for server-side implementations of PlatformTransferService</summary>
    [grpc::BindServiceMethod(typeof(PlatformTransferService), "BindService")]
    public abstract partial class PlatformTransferServiceBase
    {
      /// <summary>
      ///
      /// 中转初始化
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.TransferInitResponseMessage> TransferInit(global::Tangerine.Grpc.Foundation.TransferInitRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 获取中转状态
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.TransferStatusResponseMessage> GetTransferStatus(global::Tangerine.Grpc.Foundation.TransferStatusRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 托盘到中转
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.TransferTrayMoveResponse> TrayToTransfer(global::Tangerine.Grpc.Foundation.TransferTrayMoveRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 中转到托盘(新的样品ID)
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.TransferTrayMoveResponse> TransferToTray(global::Tangerine.Grpc.Foundation.TransferTrayMoveRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 中转下料位 → 相邻中转上料位（横向交接）
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.UnloadTransferToLoadTransferResponse> UnloadTransferToLoadTransfer(global::Tangerine.Grpc.Foundation.UnloadTransferToLoadTransferRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 中转上料位 → 相邻中转下料位（反向横向交接）
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.LoadTransferToUnloadTransferResponse> LoadTransferToUnloadTransfer(global::Tangerine.Grpc.Foundation.LoadTransferToUnloadTransferRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 中转正向移动
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.TransferMoveResponseMessage> TransferForward(global::Tangerine.Grpc.Foundation.TransferMoveRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///
      /// 中转反向移动
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Tangerine.Grpc.Foundation.TransferMoveResponseMessage> TransferBackward(global::Tangerine.Grpc.Foundation.TransferMoveRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(PlatformTransferServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_TransferInit, serviceImpl.TransferInit)
          .AddMethod(__Method_GetTransferStatus, serviceImpl.GetTransferStatus)
          .AddMethod(__Method_TrayToTransfer, serviceImpl.TrayToTransfer)
          .AddMethod(__Method_TransferToTray, serviceImpl.TransferToTray)
          .AddMethod(__Method_UnloadTransferToLoadTransfer, serviceImpl.UnloadTransferToLoadTransfer)
          .AddMethod(__Method_LoadTransferToUnloadTransfer, serviceImpl.LoadTransferToUnloadTransfer)
          .AddMethod(__Method_TransferForward, serviceImpl.TransferForward)
          .AddMethod(__Method_TransferBackward, serviceImpl.TransferBackward).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PlatformTransferServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_TransferInit, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.TransferInitRequest, global::Tangerine.Grpc.Foundation.TransferInitResponseMessage>(serviceImpl.TransferInit));
      serviceBinder.AddMethod(__Method_GetTransferStatus, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.TransferStatusRequest, global::Tangerine.Grpc.Foundation.TransferStatusResponseMessage>(serviceImpl.GetTransferStatus));
      serviceBinder.AddMethod(__Method_TrayToTransfer, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.TransferTrayMoveRequest, global::Tangerine.Grpc.Foundation.TransferTrayMoveResponse>(serviceImpl.TrayToTransfer));
      serviceBinder.AddMethod(__Method_TransferToTray, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.TransferTrayMoveRequest, global::Tangerine.Grpc.Foundation.TransferTrayMoveResponse>(serviceImpl.TransferToTray));
      serviceBinder.AddMethod(__Method_UnloadTransferToLoadTransfer, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.UnloadTransferToLoadTransferRequest, global::Tangerine.Grpc.Foundation.UnloadTransferToLoadTransferResponse>(serviceImpl.UnloadTransferToLoadTransfer));
      serviceBinder.AddMethod(__Method_LoadTransferToUnloadTransfer, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.LoadTransferToUnloadTransferRequest, global::Tangerine.Grpc.Foundation.LoadTransferToUnloadTransferResponse>(serviceImpl.LoadTransferToUnloadTransfer));
      serviceBinder.AddMethod(__Method_TransferForward, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.TransferMoveRequest, global::Tangerine.Grpc.Foundation.TransferMoveResponseMessage>(serviceImpl.TransferForward));
      serviceBinder.AddMethod(__Method_TransferBackward, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tangerine.Grpc.Foundation.TransferMoveRequest, global::Tangerine.Grpc.Foundation.TransferMoveResponseMessage>(serviceImpl.TransferBackward));
    }

  }
}
#endregion
